import { Car } from "../interfaces/Car";

export const getCarros = (): Car[] => {
  return [
    {
      id: "1",
      title: "Volkswagen Golf",
      slug: "volkswagen-golf",
      price: 85000,
      year: 2018,
      km: 45000,
      description: "Test",
      hero_image: "/images/car1.jpg",
      hero_image_alt: "Volkswagen Golf",
    },
    {
      id: "2",
      title: "Honda Civic",
      slug: "honda-civic",
      price: 95000,
      year: 2019,
      km: 38000,
      description: "Test",
      hero_image: "/images/civic-2023.jpg",
      hero_image_alt: "Honda Civic",
    },
    {
      id: "3",
      title: "Ford Ka",
      slug: "ford-ka",
      price: 42000,
      year: 2017,
      km: 72000,
      description: "Test",
      hero_image: "/images/car3.jpg",
      hero_image_alt: "Ford Ka",
    },
    {
      id: "4",
      title: "Chevrolet Onix",
      slug: "chevrolet-onix",
      price: 78000,
      year: 2020,
      km: 30000,
      description: "Test",
      hero_image: "/images/car4.jpg",
      hero_image_alt: "Chevrolet Onix",
    },
    {
      id: "5",
      title: "Renault Sandero",
      slug: "renault-sandero",
      price: 48000,
      year: 2016,
      km: 85000,
      description: "Test",
      hero_image: "/images/car5.jpg",
      hero_image_alt: "Renault Sandero",
    },
    {
      id: "6",
      title: "Toyota Corolla",
      slug: "toyota-corolla",
      price: 120000,
      year: 2021,
      km: 25000,
      description: "Test",
      hero_image: "/images/corolla-2024.jpg",
      hero_image_alt: "Toyota Corolla",
    },
    {
      id: "7",
      title: "Hyundai HB20",
      slug: "hyundai-hb20",
      price: 65000,
      year: 2019,
      km: 41000,
      description: "Test",
      hero_image: "/images/car7.jpg",
      hero_image_alt: "Hyundai HB20",
    },
    {
      id: "8",
      title: "Nissan Versa",
      slug: "nissan-versa",
      price: 56000,
      year: 2018,
      km: 60000,
      description: "Test",
      hero_image: "/images/car8.jpg",
      hero_image_alt: "Nissan Versa",
    },
    {
      id: "9",
      title: "Fiat Uno",
      slug: "fiat-uno",
      price: 32000,
      year: 2015,
      km: 98000,
      description: "Test",
      hero_image: "/images/car9.jpg",
      hero_image_alt: "Fiat Uno",
    },
    {
      id: "10",
      title: "Jeep Renegade",
      slug: "jeep-renegade",
      price: 110000,
      year: 2020,
      km: 40000,
      description: "Test",
      hero_image: "/images/car10.jpg",
      hero_image_alt: "Jeep Renegade",
    },
    {
      id: "11",
      title: "Kia Soul",
      slug: "kia-soul",
      price: 90000,
      year: 2019,
      km: 47000,
      hero_image: "/images/car11.jpg",
      hero_image_alt: "Kia Soul",
    },
    {
      id: "12",
      title: "Audi A3",
      slug: "audi-a3",
      price: 150000,
      year: 2022,
      km: 15000,
      hero_image: "/images/car12.jpg",
      hero_image_alt: "Audi A3",
    },
  ];
};
